/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Progress = IDL.Record({
  'lastPlayed' : IDL.Int,
  'roundsPlayed' : IDL.Nat,
  'highestScore' : IDL.Nat,
});
export const Category = IDL.Variant({
  'letters' : IDL.Null,
  'numbers' : IDL.Null,
  'colors' : IDL.Null,
});
export const Question = IDL.Record({
  'answers' : IDL.Vec(IDL.Text),
  'category' : Category,
  'prompt' : IDL.Text,
});

export const idlService = IDL.Service({
  'getProgress' : IDL.Func([], [Progress], ['query']),
  'getQuestionsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'updateProgress' : IDL.Func([Category, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Progress = IDL.Record({
    'lastPlayed' : IDL.Int,
    'roundsPlayed' : IDL.Nat,
    'highestScore' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'letters' : IDL.Null,
    'numbers' : IDL.Null,
    'colors' : IDL.Null,
  });
  const Question = IDL.Record({
    'answers' : IDL.Vec(IDL.Text),
    'category' : Category,
    'prompt' : IDL.Text,
  });
  
  return IDL.Service({
    'getProgress' : IDL.Func([], [Progress], ['query']),
    'getQuestionsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'updateProgress' : IDL.Func([Category, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };